### ISSUE TITLE
kingstoncommunitynetwork.com - Front End

### ISSUE THREAD

**Issue by BitSwift-v2** [sacha-l/kingston-community-network#13]
I really think my mspaint skills do the website a dis-service.  Let me get an actual map with actual coverage areas that we could reach at this point in time.  (http://www.kingstoncommunitynetwork.com/static/media/KCN%20first%20phase.97077c9a.png)

We will also extend it up princess street to Copper Penny as I am sure they will be willing to participate.

What else, oh yea, we need SSL on the site.

**Comment by BitSwift-v2** [comment]
Hello Sacha, please update the map with this one.  https://www.dropbox.com/s/r8agfrr2ygr0ed0/Kingston_Community_Network.JPG?dl=0  .

**Comment by BitSwift-v2** [comment]
bump

**Comment by sacha-l** [comment]
Done
