### ISSUE TITLE
Add SSL

### ISSUE THREAD

**Issue by BitSwift-v2** [sacha-l/kingston-community-network#14]
We need SSL on kingstoncommunitynetwork.com or no ones going to take this seriously. 

I would suggest to use LetsEncrypt, either that or I can order a basic Comodo cert.

**Comment by sacha-l** [comment]
Getting an error on my end (see screenshot below). Are the DNS records pointing to Netlify?

![ssl-provisioning-error](https://user-images.githubusercontent.com/23283108/106058937-2cacd680-60af-11eb-9fc6-739ad22833d1.png)

**Comment by BitSwift-v2** [comment]
We set the NS record to point at dns1.p01.nsone.net , dns2.p01.nsone.net , etc.   Are these Netlify name servers ?  click the Verify DNS configuration options there, what does it say?

**Comment by sacha-l** [comment]
It worked! Probably just took some time to propagate the changes. Closing this issue now.
