### ISSUE TITLE
Connect website to domain 

### ISSUE THREAD

**Issue by sacha-l** [sacha-l/kingston-community-network#2]

**Comment by sacha-l** [comment]
Look into DID solutions for user management (e.g. IDX with https://idx.xyz/docs/libs-getting-started) 🤔

**Comment by BitSwift-v2** [comment]
which website here needs connecting to the domain?

**Comment by BitSwift-v2** [comment]
waiting on txt entry to update dns record

**Comment by sacha-l** [comment]
All connected ! See: http://www.kingstoncommunitynetwork.com/  

Closing this issue.
