### ISSUE TITLE
Brand Guide - Brand Pack 

### ISSUE THREAD

**Issue by BitSwift-v2** [sacha-l/kingston-community-network#5]
Here is the link to the brand pack, we should be using official Bitswift brand colours for all the splash pages and customer sign up pages.  Any customer facing page should follow Bitswift Brand guidelines:
[](https://www.dropbox.com/s/nys6z1hzer97e32/Bitswift_Brand_1_31_2017.zip?dl=0)

**Comment by BitSwift-v2** [comment]
https://www.dropbox.com/s/nys6z1hzer97e32/Bitswift_Brand_1_31_2017.zip?dl=0

**Comment by sacha-l** [comment]
Integrated as much of the brand pack as possible, trying to keep it minimal for now. Closing this until we open a new issue to improve the branding.
