### ISSUE TITLE
Map access point locations

### ISSUE THREAD

**Issue by BitSwift-v2** [sacha-l/kingston-community-network#8]
Create a map of the access points locations which will compose the first initiatl access points in the first phase of the KCN rollout.  

Proposed locations are Confedplace building as well as the South side of Sir Johns Public House.  Formal map needs to be done up with estimate coverage points.

This is probably a task for Paul .

**Comment by BitSwift-v2** [comment]
Rough idea of estimated coverage areas: https://bitswift-my.sharepoint.com/:i:/g/personal/admin_bitswift_onmicrosoft_com/EWRawAJZxYtPhkf5CoXB6dsB5FzIxbRpUBH0StVVDs3dgw?e=KhaZMW

**Comment by BitSwift-v2** [comment]
Currently deployed APs and coverage areas: https://bitswift-my.sharepoint.com/:i:/g/personal/admin_bitswift_onmicrosoft_com/ETRJpNR-EXFLpyMn4YoIgRwBemUqIC1GTiBx9-PKQzamtA?e=xIpcz1

**Comment by BitSwift-v2** [comment]
Map view: https://bitswift-my.sharepoint.com/:i:/g/personal/admin_bitswift_onmicrosoft_com/EZnTwpVDqa9JuTjRpnyfUsABzpFXKW0kpXoqDPK_p33d-Q?e=4Hc6Vu

**Comment by sacha-l** [comment]
Closing this issue, thanks @BitSwift-v2 for making those! I used one on the website.
